version: 0.2

#TODO: Move all constatns to environment variables
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - start-dockerd
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - cat /proc/sys/net/ipv6/conf/docker0/accept_ra

